# Generated by Django 2.0.5 on 2018-05-22 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('files', models.FileField(upload_to='media/')),
                ('attributes', models.TextField()),
                ('url', models.URLField()),
                ('date_created', models.DateField()),
            ],
        ),
    ]
